CREATE TYPE blockchain_api_service.HASH_FUNCTION AS ENUM ('IDENTITY', 'FIXED', 'KECCAK_256');
CREATE TYPE blockchain_api_service.SNAPSHOT_STATUS AS ENUM ('PENDING', 'SUCCESS', 'FAILED');
CREATE TYPE blockchain_api_service.SNAPSHOT_FAILURE_CAUSE AS ENUM ('LOG_RESPONSE_LIMIT', 'OTHER');
